name: CI

on:
  push:

jobs:
  # test always and publish on release
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
